# Generated by Django 5.1.4 on 2025-01-11 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('carbon_balance', models.IntegerField(default=0)),
                ('cash_balance', models.FloatField(default=0.0)),
                ('active_account', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_unit_price', models.FloatField(default=0)),
                ('carbon_quantity', models.FloatField(default=0)),
                ('request_reason', models.TextField()),
                ('request_status', models.CharField(default='Pending Approval', max_length=50)),
                ('request_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='companyAccount.companyaccount')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='companyAccount.companyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RequestReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_datetime', models.DateTimeField()),
                ('alert_text', models.TextField()),
                ('alert_status', models.CharField(max_length=50)),
                ('alert_view_date', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companyAccount.outstandingrequest')),
            ],
        ),
    ]
