# Generated by Django 4.2.17 on 2025-01-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestreceived',
            name='request',
        ),
        migrations.DeleteModel(
            name='OutstandingRequest',
        ),
        migrations.DeleteModel(
            name='RequestReceived',
        ),
    ]
