# Generated by Django 4.2.17 on 2025-01-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyAccount', '0002_remove_requestreceived_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaccount',
            old_name='active_account',
            new_name='activeAccount',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='carbon_balance',
            new_name='carbonBalance',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='cash_balance',
            new_name='cashBalance',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='company_name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='created_datetime',
            new_name='createdDatetime',
        ),
        migrations.RenameField(
            model_name='companyaccount',
            old_name='updated_datetime',
            new_name='updatedDatetime',
        ),
    ]
