# Generated by Django 5.1.4 on 2025-01-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstandingRequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='target_company',
            new_name='company',
        ),
    ]
