# Generated by Django 4.2.17 on 2025-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstandingRequest', '0002_rename_target_company_outstandingrequest_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='carbon_quantity',
            new_name='carbonQuantity',
        ),
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='created_datetime',
            new_name='createdDatetime',
        ),
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='request_reason',
            new_name='requestReason',
        ),
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='request_status',
            new_name='requestStatus',
        ),
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='request_type',
            new_name='requestType',
        ),
        migrations.RenameField(
            model_name='outstandingrequest',
            old_name='updated_datetime',
            new_name='updatedDatetime',
        ),
        migrations.RemoveField(
            model_name='outstandingrequest',
            name='carbon_unit_price',
        ),
        migrations.AddField(
            model_name='outstandingrequest',
            name='carbonUnitPrice',
            field=models.FloatField(default=0),
        ),
    ]
