# Generated by Django 4.2.17 on 2025-01-11 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outstandingRequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_datetime', models.DateTimeField()),
                ('alert_text', models.TextField()),
                ('alert_status', models.CharField(max_length=50)),
                ('alert_view_date', models.DateTimeField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='outstandingRequest.outstandingrequest')),
            ],
        ),
    ]
