# Generated by Django 4.2.17 on 2025-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestReceived', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestreceived',
            old_name='alert_datetime',
            new_name='alertDatetime',
        ),
        migrations.RenameField(
            model_name='requestreceived',
            old_name='alert_status',
            new_name='alertStatus',
        ),
        migrations.RenameField(
            model_name='requestreceived',
            old_name='alert_text',
            new_name='alertText',
        ),
        migrations.RenameField(
            model_name='requestreceived',
            old_name='alert_view_date',
            new_name='alertViewDate',
        ),
        migrations.RenameField(
            model_name='requestreceived',
            old_name='created_datetime',
            new_name='createdDatetime',
        ),
        migrations.RemoveField(
            model_name='requestreceived',
            name='updated_datetime',
        ),
        migrations.AddField(
            model_name='requestreceived',
            name='updatedDatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
